sudo: false
language: python
cache: pip
python:
- 3.6
script:
- ./create_deployment_pkg
deploy:
  provider: lambda
  function_name: commute-weather
  description: Tells you each week day morning whether you need to take your umbrella
  region: us-east-1
  role: arn:aws:iam::158438328645:role/service-role/commute-weather-role
  runtime: python3.6
  module_name: weather
  handler_name: lambda_handler
  zip: /dev/shm/deploy.zip
  timeout: 10
  memory_size: 128
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  on:
    branch: latest
