sudo: false
language: python
cache: pip
python:
- 3.6
script:
- ./create_deployment_pkg
- ls -lhR
deploy:
  provider: lambda
  function_name: commute-weather
  description: Tells you each week day morning whether you need to take your umbrella
  region: us-east-1
  role: arn:aws:iam::158438328645:role/service-role/commute-weather-role
  runtime: python3.6
  module_name: weather
  handler_name: lambda_handler
  zip: deploy
  timeout: 10
  memory_size: 128
  access_key_id:
    secure: MWNpFkSq8u3xPvHJXf2O0pS+R8jaFPHzpNn36Fez2rMq9G0id8lABBWFVTCT/n/MAMsuG/+dephL3TfiSZJ1Pma+59Dw1HZ/cxc/7Fct5h9STfqNIBr19qyKtjbVjaEQmvq1kCKACqtjdYryX8mfTAOLarx/szf2M29hNxSqNY0b1TPdzXDC8pvIlDKN67RroEh8EE4pqKK34VsgBk4Sy08D8GlHgp8bCR92Sd2Go6zqyFULgrIep3wIXk9fVUNWQoIeDAOnCqzcmvicsidOXUaNEPRDSrY8om4rADzDirMsQDyPMI1Kgs4egugbYkzuEVV4DYgPXIgvpoq72V18mB7/akJX8nVhaE5MQn0YQqTbg+NS5U9ObpkHLvu83G4HMbMOY2dHfuHqgfgJBF0jgP6draKsvh48QD3lTRiKxqDhMV5xKT85rQMeH5JwSUiI8nsPT1NntwzKTr3ucGWjRmtyhSb+avhg0qRUUBSpI7VMZRe4C/iRmUhPkd6DMxLv/rB+vYAWStO+9uIyadpR+t+VVM7K7eL5FotXU2ubb2bRSajx3WMG/E/9Fn3s84Vd3PBSPlOXZ+505O5by8dlrPawTEPKBw7exv/CeVPnKXv9DkXv1lXkhgtm4wZFSvaH8ir/tTu56StUIOIP987pm4/3BdswsAMQxweIPZ5UHW0=
  secret_access_key:
    secure: xENKdEqA97pnnAaOvWHSuSzr0oihotqyF/xIVMcwTeMH+5jZ76pZ6t/JOOwRkgyMGPmNK7qZWaQ0cvtSt8pwKo45wOQnSF8JHceLOoPumJ1KVrKkd9KyKo3riwkLLLlBld6s3aPhi2cdbSerV/KQW/CO5FjA2eZMtbCKG2+iiAEztlvzZjhUaujo7LTUfyZmHLvZ5GF1nmEkAQhKcsD51Nr/nvTS6LpLnQKWUV9Vf+fnx+saln5LbszIQGafpPttJVRLGw6zT+rBOcbS+K+Ox1hmQCU5K7TBw/fo7VcNxxtO/LPmYaoD0/laOX6DlB7z/8bPgwEx+Ae/yALjwkGdZKJv2+gfIg3kfaTcQiBt1QUtHS77Ux21J9vpEVdIUYGxwLUJKxtIVNEjBmNbfsxqfgMBYC5uvq2i2OOh2ntwuQDn7wHMupmVc9GCiSN9ZkzB/BRzsVAa23IB2k5R53CE/zFWABAQ7ZtjpE2PggWm2v7R7yNFGv0ucmiad8ZWZoejyEWXxB8QATzUwCD0sdLJKvyx9jjXi+NIV55/GM1DmArPY4VvnCe2VuzO2qgKPoh7HiCzKqVLbK0l4p0NM4TH5PwIiMEgQB3k8u2KsUiMctGkBrX1IqzTtjteTTnUyr1h6Co4bShdFhoJ4Kf4nupZKxhjs0C+IUBWS3tgR479FII=
  on:
    branch: latest
