#!/bin/bash

readonly OUTPUT_DIR="deploy"
readonly OUTPUT_ZIP="deploy.zip"  # must match .travis.yml
readonly DEPENDENCIES="$VIRTUAL_ENV/lib/python3.6/site-packages"

echo "Working directory: $PWD"

if [[ -d $OUTPUT_DIR ]]; then
    echo "Output dir already exists" >&2
    exit 1
fi

mkdir "$OUTPUT_DIR"
rsync -a "$DEPENDENCIES/" "$OUTPUT_DIR"
rsync -a commute_weather/ "$OUTPUT_DIR"
du -sh "$OUTPUT_DIR"

cd "$OUTPUT_DIR"  # cannot have container dir in zip
zip -qr9 "$OUTPUT_ZIP" .
cd - > /dev/null
du -sh "$OUTPUT_ZIP"
