#!/bin/bash

readonly OUTPUT_DIR="deploy"
readonly OUTPUT_ZIP="deploy.zip"  # must match .travis.yml
readonly DEPENDENCIES="$VIRTUAL_ENV/lib/python3.6/site-packages"

if [[ -d $OUTPUT_DIR ]]; then
    echo "Output dir already exists" >&2
    exit 1
fi

mkdir "$OUTPUT_DIR"
rsync -a "$DEPENDENCIES/" "$OUTPUT_DIR"
rsync -a commute_weather/ "$OUTPUT_DIR"
du -sh "$OUTPUT_DIR"

zip -qr -9 "$OUTPUT_ZIP" "$OUTPUT_DIR"
ls -lh "$OUTPUT_ZIP"
